#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root"
   exit
fi

MACPORTS_GIT_SOURCE=/opt/src/macports-git

cd $MACPORTS_GIT_SOURCE &&
git stash &&
git checkout master &&
git pull upstream master &&
git push origin master
sudo port -v sync
